name: advancednaql
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^0.1.2
  adobe_xd: ^0.1.3
  firebase_auth: ^0.16.0
  firebase_database: ^3.0.4
  firebase_storage: ^3.0.3
  smooth_star_rating: ^1.1.1
  google_sign_in:
  intl: 
  image: ^2.0.4
  toast: ^0.1.3
  firebase_core: ^0.4.0+6
  progress_dialog: ^1.1.0+1
  fluttertoast: ^3.1.3
  flutter_svg: ^0.17.4
  flutter_spinkit: "^4.1.2"
  connectivity: ^0.4.8+6
  shared_preferences: ^0.5.7+3
  flutter_screenutil: ^0.4.2
  image_picker: ^0.6.6+5
  path_provider: ^1.6.9
  flutter_image_compress: ^0.6.8
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.10
  flutter_rating_bar: ^2.0.0
  firebase_messaging: ^5.1.2
  flutter_local_notifications:
  fimber: ^0.4.0
  google_maps_flutter: 
  geolocator:
  access_settings_menu: ^0.0.1
  flutter_alert: ^0.4.0
  rflutter_alert: ^1.0.3
  font_awesome_flutter: ^8.8.1
  geoflutterfire: ^2.0.3+2
  location: ^2.3.5
  flutter_slidable: ^0.5.4
  uuid: ^2.2.0

  #simple_slider: ^0.0.2
  rxdart:
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/antenna.png
   - assets/logo.png
   - assets/logowhite.png
   - assets/carhorn.mp3
   - assets/images/ic_lang.png
   - assets/images/ic_policy.png
   - assets/images/ic_privcy.png
   - assets/images/ic_volum.png
   - assets/images/ic_typeprovider.png
   - assets/images/ic_typeuser.png
   - assets/images/ic_movetime.png
   - assets/images/ic_car.png
   - assets/images/ic_wbcar.png
   - assets/images/ic_wcar.png
   - assets/images/ic_compny.png
   - assets/images/ic_driver.png
   - assets/images/ic_modelcar.png
   - assets/images/ic_mycar.png
   - assets/images/ic_location.png
   - assets/images/ic_location2.png
   - assets/images/pin_red.png
   - assets/images/pin_green.png
   - assets/images/ic_wlocation.png
   - assets/images/ic_bluecar.png
   - assets/images/ic_ads.png
   - assets/images/image_privcy_policy.png
   - assets/images/image_terms_use.png
   - assets/images/ic_agricultural_equipment.png
   - assets/images/ic_average_transfer.png
   - assets/images/ic_heavy_Equipment.png
   - assets/images/ic_heavy_transport.png
   - assets/images/ic_light_transmission.png
   - assets/images/ic_passenger_transport.png
   - assets/images/ic_person.png
   - lang/en.json
   - lang/ar.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
